### PR TITLE
remove jquery dependency to avoid conflict, closes #7

### LINKED ISSUE #7: htmlwidgets no render with fullPage
Hi everyone! 

Thanks @JohnCoene  for this!

I can't render htmlwidgets using `fullPage` (I can in `pagePiling`) the only widget that I tested and works is `shiny::dataTableOutput`. The error in the console is:

image

Can you guide me please to solve this problem?

Some test app to replicate.

```r
# ui.R
fullPage(
    menu = c("Full Page" = "link1"),
    fullSection(
        menu = "intro",
        "Widget testings",
        # echarts4r::echarts4rOutput("widget")
        # highcharter::highchartOutput("widget")
        # plotly::plotlyOutput("widget")
        # leaflet::leafletOutput("widget")
        # DT::dataTableOutput("widget")
        shiny::dataTableOutput("widget")
    )
)
```

```r
# server.R
function(input, output){
    
    output$widget <- 
        # echarts4r::renderEcharts4r({
            # mtcars %>% echarts4r::e_charts(Sepal.Length) %>% echarts4r::e_scatter(Petal.Length)

        # highcharter::renderHighchart({
        #     highcharter::hchart(iris, "scatter", highcharter::hcaes(Sepal.Length, Petal.Length))

         # plotly::renderPlotly({
         #     plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
        
        # leaflet::renderLeaflet({
        #     leaflet::leaflet() %>% leaflet::addTiles()
    
        # DT::renderDataTable({
        #     iris
    
        shiny::renderDataTable({
            iris
    
    
    })
   
}
```

### PR DESCRIPTION
**Pull request by etiennebacher**
As pointed out in #7, htmlwidgets couldn't be displayed when using `fullPage()`. The reason mentioned [here](https://github.com/ramnathv/htmlwidgets/issues/253#issuecomment-309599829) is that there's a conflict between `jquery` calls made by `shiny` and `fullPage`. Therefore, this PR removes the call to `jquery.min.js` (present in `fullPage()` and `multiPage()`), which is the reason why htmlwidgets were not displayed. 

Here are some examples provided in #7, all htmlwidgets in this can be rendered with the fixed version:
```
library(shiny)
library(echarts4r)
library(highcharter)
library(plotly)
library(leaflet)
library(DT)

ui <- fullPage(
  menu = c("Full Page" = "link1"),
  fullSection(
    menu = "intro",
    "Widget testings",
    # echarts4r::echarts4rOutput("widget")
    # highcharter::highchartOutput("widget")
    # plotly::plotlyOutput("widget")
    # leaflet::leafletOutput("widget")
    # DT::dataTableOutput("widget")
    shiny::dataTableOutput("widget")
  )
)

server <- function(input, output){
  
    output$widget <- 
      # echarts4r::renderEcharts4r({
      # iris %>% echarts4r::e_charts(Sepal.Length) %>% echarts4r::e_scatter(Petal.Length)
      
      # highcharter::renderHighchart({
      #     highcharter::hchart(iris, "scatter", highcharter::hcaes(Sepal.Length, Petal.Length))
      
      # plotly::renderPlotly({
      #     plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
      
      # leaflet::renderLeaflet({
      #     leaflet::leaflet() %>% leaflet::addTiles()
    
    # DT::renderDataTable({
    #     iris
    
    shiny::renderDataTable({
      iris
      
      
    })
    
  }

shinyApp(ui, server)
```

### CODE REVIEW

**Comment by etiennebacher** [comment]
Hi, I think this PR solves the issue with htmlwidgets. Could you verify and accept it if it works?

**Comment by JohnCoene** [comment]
I'm not sure we should remove the easing, I do not think that's included in jQuery core. For the rest, it seems you are correct; shiny loads `shared` libraries (including jQuery) so there is no need for it here: it causes clashes.

**Comment by etiennebacher** [comment]
I didn't remove the easing, only `jquery-3.2.1/jquery.min.js`

**Comment by JohnCoene** [comment]
My bad sorry.

**Pull request merged**
